<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class modelsUserProxy extends \models\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setPassword($password)
    {
        $this->_load();
        return parent::setPassword($password);
    }

    public function setGroup(\models\UserGroup $group)
    {
        $this->_load();
        return parent::setGroup($group);
    }

    public function getGroup()
    {
        $this->_load();
        return parent::getGroup();
    }

    public function setCountry(\models\Country $country)
    {
        $this->_load();
        return parent::setCountry($country);
    }

    public function getWishlists()
    {
        $this->_load();
        return parent::getWishlists();
    }

    public function authenticate()
    {
        $this->_load();
        return parent::authenticate();
    }

    public function isAdmin()
    {
        $this->_load();
        return parent::isAdmin();
    }

    public function toArray()
    {
        $this->_load();
        return parent::toArray();
    }

    public function __call($method, $args)
    {
        $this->_load();
        return parent::__call($method, $args);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'password', 'email', 'country', 'user_group', 'wishlists');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}