<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class modelsWishlistProxy extends \models\Wishlist implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function setUser(\models\User $user)
    {
        $this->_load();
        return parent::setUser($user);
    }

    public function getWishlistItems()
    {
        $this->_load();
        return parent::getWishlistItems();
    }

    public function getItems()
    {
        $this->_load();
        return parent::getItems();
    }

    public function toArray()
    {
        $this->_load();
        return parent::toArray();
    }

    public function __call($method, $args)
    {
        $this->_load();
        return parent::__call($method, $args);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'url_title', 'user', 'wishlist_items');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}